import { Poppins } from '@next/font/google';
import type { Metadata } from 'next';

import './globals.css';
import Footer from '@/view/Footer/Footer';
import Nav from '@/view/Nav/Nav';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const poppins = Poppins({
  subsets: ['latin-ext'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body className={`mx-auto max-w-[1920px] ${poppins.variable}`}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
